@isTest
public with sharing class ActionItemImportBatchTest {

    static testMethod void ActionItemImportBatchTest() {
        // Commitments__c com = new Commitments__c(ExternalID__c='1123000000UComTest');
        // insert com;

        // Action_Item__c  ai = new Action_Item__c(Former_Commitment__c='1123000000UComTest');
        // insert ai;

        // Test.StartTest();
        // ActionItemImportBatch actionItemImportBatch = new ActionItemImportBatch();
        // ID batchprocessid = Database.executeBatch(actionItemImportBatch);
        // Test.StopTest();
		
        // Action_Item__c aiTest = [SELECT Id, Commitment__c FROM Commitment__c limit 1];
        // System.assertEquals(com.Id, aiTest.Commitment__c);
    }
}