public class ConvertJsonToOBject {
    public String Active;
    public String Address;
    public String CustomerName;
    public String Email;
    public String Mobile;
	/*public List<ConvertJsonToOBject> account;
    public class result{
        public String Active;
        public String Address;
        public String CustomerName;
        public String Email;
        public String Mobile;
    }
    
    public class JSON {
        public String status;
		public List<ConvertJsonToOBject> ListAcc;
        public String Error;
	}
	public static ConvertJsonToOBject parse(String json){
		return (ConvertJsonToOBject) System.JSON.deserialize(json, ConvertJsonToOBject.class);
	}*/
}